name: Build and obfuscate

on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: ADSearch.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run NuGet restore
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build ADSearch.exe
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    
    - name: Upload ADSearch.exe
      uses: actions/upload-artifact@v4
      with:
        name: ADSearch.exe
        path: ADSearch\bin\Release\ADSearch.exe

    - name: Setup DotFuscator
      run: |
        7z x Dotfuscator\DotfuscatorCE.zip
        mkdir -p $env:USERPROFILE\AppData\Local\"PreEmptive Solutions"\"Dotfuscator Community Edition"\6.0 -erroraction 'silentlycontinue'
        cp DotfuscatorCE\license\* $env:USERPROFILE\AppData\Local\"PreEmptive Solutions"\"Dotfuscator Community Edition"\6.0\

    - name: Build obfuscated versions
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: DotfuscatorCE\dotfuscator.exe "Dotfuscator\dotfuscator_config.xml"
    
    - name: directory listing
      run: Get-ChildItem -Recurse

    #- name: Upload obfuscated version
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ADSearch_Obfuscated.exe
    #    path: ADSearch_Obfuscated.exe
